import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer';
import { ResumeData, ResumeTemplate } from '@/store/useResumeStore';

// Register fonts if needed, but we'll use standard ones for compatibility
// Standard PDF fonts: Helvetica, Times-Roman, Courier, Symbol, ZapfDingbats

const styles = StyleSheet.create({
  page: {
    padding: 50,
    backgroundColor: '#FFFFFF',
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 30,
    borderBottomWidth: 1.5,
    borderBottomColor: '#000000',
    paddingBottom: 20,
  },
  name: {
    fontSize: 32,
    fontFamily: 'Times-Roman',
    color: '#000000',
    letterSpacing: -0.5,
    textTransform: 'uppercase',
  },
  email: {
    fontSize: 10,
    color: '#444444',
    marginTop: 4,
    fontFamily: 'Helvetica',
  },
  section: {
    marginTop: 25,
  },
  sectionTitle: {
    fontSize: 9,
    fontFamily: 'Helvetica',
    fontWeight: 'bold',
    color: '#000000',
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 1.5,
  },
  line: {
    height: 0.5,
    backgroundColor: '#000000',
    marginBottom: 12,
  },
  content: {
    fontSize: 10,
    color: '#1a1a1a',
    lineHeight: 1.5,
    fontFamily: 'Times-Roman',
  },
  footer: {
    position: 'absolute',
    bottom: 40,
    left: 50,
    right: 50,
    borderTopWidth: 0.5,
    borderTopColor: '#000000',
    paddingTop: 10,
    fontSize: 7,
    color: '#666666',
    textTransform: 'uppercase',
    letterSpacing: 1,
  }
});

interface ResumePDFProps {
  data: ResumeData;
  template: ResumeTemplate;
}

const ResumePDF = ({ data, template }: ResumePDFProps) => {
  const isMinimal = template === 'minimal';
  const isExecutive = template === 'executive';

  return (
    <Document>
      <Page size="A4" style={[styles.page, isExecutive ? { padding: 80 } : {}]}>
        {/* Header */}
        <View style={[
          styles.header, 
          isMinimal ? { borderBottomWidth: 0, textAlign: 'center' } : {}, 
          isExecutive ? { borderBottomWidth: 2, borderBottomColor: '#1e293b' } : {}
        ]}>
          <Text style={[
            styles.name, 
            isMinimal ? { fontSize: 32, textTransform: 'uppercase' } : {}, 
            isExecutive ? { fontSize: 36, fontStyle: 'italic' } : {}
          ]}>
            {data.name || 'FULL NAME'}
          </Text>
          <View style={{ flexDirection: 'row', gap: 10, marginTop: 5, justifyContent: isMinimal ? 'center' : 'flex-start' }}>
            <Text style={styles.email}>{data.email || 'email@example.com'}</Text>
            {data.phone && <Text style={styles.email}>• {data.phone}</Text>}
            {data.location && <Text style={styles.email}>• {data.location}</Text>}
          </View>
        </View>

        {/* Summary */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Professional Summary</Text>
          <View style={styles.line} />
          <Text style={styles.content}>{data.summary || 'Summary...'}</Text>
        </View>

        {/* Skills */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Technical Expertise</Text>
          <View style={styles.line} />
          <Text style={styles.content}>{data.skills || 'Skills...'}</Text>
        </View>

        {/* Experience */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Professional Experience</Text>
          <View style={styles.line} />
          <Text style={styles.content}>{data.experience || 'Experience...'}</Text>
        </View>

        {/* Education */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Education</Text>
          <View style={styles.line} />
          <Text style={styles.content}>{data.education || 'Education...'}</Text>
        </View>

        {/* Projects */}
        {data.projects && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Key Projects</Text>
            <View style={styles.line} />
            <Text style={styles.content}>{data.projects}</Text>
          </View>
        )}

        <Text style={styles.footer}>Generated by Resuml Premium AI</Text>
      </Page>
    </Document>
  );
};

export default ResumePDF;
